USE master;
GO

IF DB_ID('XaaDirDB') IS NOT NULL
BEGIN
    ALTER DATABASE XaaDirDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE XaaDirDB;
END
GO

PRINT 'XaaDirDB dropped successfully.';
GO
